version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    expose:
      - 5432
    ports:
      - 5434:5432
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6449:6379
  nats:
    image: nats
    expose:
      - 4222
    ports:
      - 4224:4222
  minio:
    image: minio/minio
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    expose:
      - 9000
    ports:
      - 9000:9000
  worker-svc:
    image: ghcr.io/kelompok-gallium-super-bootcamp/tm-svc:latest
    command: ["svc:start", "--", "worker"]
    depends_on:
      - postgres
      - redis
      - nats
      - minio
    environment:
      tm_database__host: postgres
      tm_database__port: 5432
      tm_database__username: postgres
      tm_database__password: postgres
      tm_database__database: tm
      tm_storage__endPoint: "172.18.0.5"
      tm_storage__port: 9000
      tm_storage__accessKey: minio
      tm_storage__secretKey: miniostorage
      todo_serverWorker__port: 7001
    ports:
      - 7001:7001
  task-svc:
    image: ghcr.io/kelompok-gallium-super-bootcamp/tm-svc:latest
    command: ["svc:start", "--", "task"]
    depends_on:
      - postgres
      - redis
      - nats
      - minio
      - worker-svc
    environment:
      tm_database__host: postgres
      tm_database__port: 5432
      tm_database__username: postgres
      tm_database__password: postgres
      tm_database__database: tm
      tm_storage__endPoint: minio
      tm_storage__port: 9000
      tm_storage__accessKey: minio
      tm_storage__secretKey: miniostorage
      todo_serverTask__port: 7002
    ports:
      - 7002:7002
  perf-svc:
    image: ghcr.io/kelompok-gallium-super-bootcamp/tm-svc:latest
    command: ["svc:start", "--", "performance"]  
    depends_on:
      - postgres
      - redis
      - nats
      - minio
    environment:
      tm_database__host: postgres
      tm_database__port: 5432
      tm_database__username: postgres
      tm_database__password: postgres
      tm_database__database: tm
      tm_storage__endPoint: minio
      tm_storage__port: 9000
      tm_storage__accessKey: minio
      tm_storage__secretKey: miniostorage
      todo_serverPerformance__port: 7003
    ports:
      - 7003:7003
  
